// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: pb/calculator.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CalcutorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Num1          float64                `protobuf:"fixed64,1,opt,name=num1,proto3" json:"num1,omitempty"`
	Num2          float64                `protobuf:"fixed64,2,opt,name=num2,proto3" json:"num2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalcutorRequest) Reset() {
	*x = CalcutorRequest{}
	mi := &file_pb_calculator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalcutorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalcutorRequest) ProtoMessage() {}

func (x *CalcutorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_calculator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalcutorRequest.ProtoReflect.Descriptor instead.
func (*CalcutorRequest) Descriptor() ([]byte, []int) {
	return file_pb_calculator_proto_rawDescGZIP(), []int{0}
}

func (x *CalcutorRequest) GetNum1() float64 {
	if x != nil {
		return x.Num1
	}
	return 0
}

func (x *CalcutorRequest) GetNum2() float64 {
	if x != nil {
		return x.Num2
	}
	return 0
}

type CalcutorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        float64                `protobuf:"fixed64,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalcutorResponse) Reset() {
	*x = CalcutorResponse{}
	mi := &file_pb_calculator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalcutorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalcutorResponse) ProtoMessage() {}

func (x *CalcutorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_calculator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalcutorResponse.ProtoReflect.Descriptor instead.
func (*CalcutorResponse) Descriptor() ([]byte, []int) {
	return file_pb_calculator_proto_rawDescGZIP(), []int{1}
}

func (x *CalcutorResponse) GetResult() float64 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_pb_calculator_proto protoreflect.FileDescriptor

const file_pb_calculator_proto_rawDesc = "" +
	"\n" +
	"\x13pb/calculator.proto\x12\n" +
	"calculator\"9\n" +
	"\x0fCalcutorRequest\x12\x12\n" +
	"\x04num1\x18\x01 \x01(\x01R\x04num1\x12\x12\n" +
	"\x04num2\x18\x02 \x01(\x01R\x04num2\"*\n" +
	"\x10CalcutorResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x01R\x06result2\x95\x01\n" +
	"\n" +
	"Calculator\x12@\n" +
	"\x03Add\x12\x1b.calculator.CalcutorRequest\x1a\x1c.calculator.CalcutorResponse\x12E\n" +
	"\bSubtract\x12\x1b.calculator.CalcutorRequest\x1a\x1c.calculator.CalcutorResponseB\x0fZ\rcalculator/pbb\x06proto3"

var (
	file_pb_calculator_proto_rawDescOnce sync.Once
	file_pb_calculator_proto_rawDescData []byte
)

func file_pb_calculator_proto_rawDescGZIP() []byte {
	file_pb_calculator_proto_rawDescOnce.Do(func() {
		file_pb_calculator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_calculator_proto_rawDesc), len(file_pb_calculator_proto_rawDesc)))
	})
	return file_pb_calculator_proto_rawDescData
}

var file_pb_calculator_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pb_calculator_proto_goTypes = []any{
	(*CalcutorRequest)(nil),  // 0: calculator.CalcutorRequest
	(*CalcutorResponse)(nil), // 1: calculator.CalcutorResponse
}
var file_pb_calculator_proto_depIdxs = []int32{
	0, // 0: calculator.Calculator.Add:input_type -> calculator.CalcutorRequest
	0, // 1: calculator.Calculator.Subtract:input_type -> calculator.CalcutorRequest
	1, // 2: calculator.Calculator.Add:output_type -> calculator.CalcutorResponse
	1, // 3: calculator.Calculator.Subtract:output_type -> calculator.CalcutorResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_calculator_proto_init() }
func file_pb_calculator_proto_init() {
	if File_pb_calculator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_calculator_proto_rawDesc), len(file_pb_calculator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_calculator_proto_goTypes,
		DependencyIndexes: file_pb_calculator_proto_depIdxs,
		MessageInfos:      file_pb_calculator_proto_msgTypes,
	}.Build()
	File_pb_calculator_proto = out.File
	file_pb_calculator_proto_goTypes = nil
	file_pb_calculator_proto_depIdxs = nil
}
